name: "PR Workflow"

on:
  pull_request:
    branches:
      - "master"

jobs:
  pr:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"

      - name: "Configure environment"
        uses: "./.github/actions/env"

      - name: "Run checks"
        uses: "./.github/actions/check"

      - name: "Build"
        run: "yarn build"
