name: "PR Workflow"

on:
  pull_request:
    branches:
      - "master"

jobs:
  pr:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"

      - name: "Get yarn cache path"
        id: "yarn-cache"
        run: 'echo "::set-output name=dir::$(yarn cache dir)"'
        shell: "bash"

      - name: "Enable node"
        uses: "actions/setup-node@master"
        with:
          node-version: "14.x"

      - name: "Load yarn cache"
        uses: "actions/cache@v2"
        with:
          path: "${{ steps.yarn-cache.outputs.dir }}"
          key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: "Install dependencies"
        run: "yarn install --frozen-lockfile"

      - name: "Run checks"
        uses: "./.github/actions/check"

      - name: "Build"
        run: "yarn build"
